'use client';

import { useState, FormEvent } from 'react';

interface ChatInputProps {
  onSubmit: (message: string) => void;
  disabled?: boolean;
  placeholder?: string;
  suggestions?: string[];
  onSuggestionClick?: (suggestion: string) => void;
}

export function ChatInput({
  onSubmit,
  disabled,
  placeholder = "Describe a news event you'd like to understand better...",
  suggestions,
  onSuggestionClick,
}: ChatInputProps) {
  const [input, setInput] = useState('');

  const handleSubmit = (e: FormEvent) => {
    e.preventDefault();
    if (input.trim() && !disabled) {
      onSubmit(input.trim());
      setInput('');
    }
  };

  return (
    <div className="border-t border-[#D6D3D1] bg-white p-4">
      <div className="max-w-3xl mx-auto">
        {suggestions && suggestions.length > 0 && (
          <div className="flex flex-wrap gap-2 mb-3">
            {suggestions.map((suggestion, i) => (
              <button
                key={i}
                onClick={() => onSuggestionClick?.(suggestion)}
                disabled={disabled}
                className="text-sm px-3 py-1 bg-[#F5F5F4] hover:bg-[#E7E5E4] rounded-full text-[#1C1917] border border-[#D6D3D1] hover:border-[#6B8E6F] disabled:opacity-50 transition-all hover:scale-105"
              >
                {suggestion}
              </button>
            ))}
          </div>
        )}
        <form onSubmit={handleSubmit} className="flex gap-2">
          <input
            type="text"
            value={input}
            onChange={(e) => setInput(e.target.value)}
            placeholder={placeholder}
            disabled={disabled}
            className="flex-1 px-4 py-2 border border-[#D6D3D1] rounded-lg focus:outline-none focus:ring-2 focus:ring-[#F59E0B] focus:border-transparent disabled:opacity-50 bg-white text-[#1C1917] placeholder:text-[#78716C]"
          />
          <button
            type="submit"
            disabled={disabled || !input.trim()}
            className="px-6 py-2 bg-[#475569] text-white rounded-lg hover:bg-[#334155] disabled:opacity-50 disabled:cursor-not-allowed transition-all hover:scale-105 hover:shadow-md font-medium"
          >
            Analyze
          </button>
        </form>
        <p className="text-xs text-[#78716C] mt-2 text-center">
          Analysis generated by AI. Please verify with primary sources.
        </p>
      </div>
    </div>
  );
}
